services:
  - type: web
    name: shutter-shy
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeployTrigger: commit
